# Generated by Django 3.2.9 on 2021-12-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='qualite',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='redacteur',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='stockage',
            field=models.BooleanField(default=False),
        ),
    ]
