# Generated by Django 3.2.9 on 2022-01-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
