# Generated by Django 3.2.9 on 2022-01-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_rubrique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
    ]
