# Generated by Django 3.2.9 on 2022-02-03 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20220201_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 15, 33, 39, 832351, tzinfo=utc)),
        ),
    ]
