# Generated by Django 3.2.9 on 2022-02-03 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogpost_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
