# Generated by Django 3.2.9 on 2022-02-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blogpost_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
