# Generated by Django 3.2.9 on 2022-03-17 14:08

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_newspost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisDeRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('edit', 'A publier'), ('suspendu', 'Parution Suspendu')], default='draft', max_length=10),
        ),
    ]
