# Generated by Django 3.2.9 on 2022-03-18 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20220317_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisderecherche',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
