# Generated by Django 3.2.9 on 2022-05-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_avisderecherche_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisderecherche',
            name='archiver',
            field=models.BooleanField(default=False),
        ),
    ]
